/*
 * Copyright (c) 2009 Xilinx, Inc.  All rights reserved.
 *
 * Xilinx, Inc.
 * XILINX IS PROVIDING THIS DESIGN, CODE, OR INFORMATION "AS IS" AS A
 * COURTESY TO YOU.  BY PROVIDING THIS DESIGN, CODE, OR INFORMATION AS
 * ONE POSSIBLE   IMPLEMENTATION OF THIS FEATURE, APPLICATION OR
 * STANDARD, XILINX IS MAKING NO REPRESENTATION THAT THIS IMPLEMENTATION
 * IS FREE FROM ANY CLAIMS OF INFRINGEMENT, AND YOU ARE RESPONSIBLE
 * FOR OBTAINING ANY RIGHTS YOU MAY REQUIRE FOR YOUR IMPLEMENTATION.
 * XILINX EXPRESSLY DISCLAIMS ANY WARRANTY WHATSOEVER WITH RESPECT TO
 * THE ADEQUACY OF THE IMPLEMENTATION, INCLUDING BUT NOT LIMITED TO
 * ANY WARRANTIES OR REPRESENTATIONS THAT THIS IMPLEMENTATION IS FREE
 * FROM CLAIMS OF INFRINGEMENT, IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.
 *
 */

#include "xil_types.h"
#include "xparameters.h"

#define GTX

#define DRP_COMMON_OFFSET 0x1000

//Used as an index for arrays drp_addr, drp_mask, drp_start_bit
#define ES_CONTROL        0
#define ES_HORZ_OFFSET    1
#define ES_PRESCALE       2
#define ES_VERT_OFFSET    3
#define ES_CONTROL_STATUS 4
#define ES_ERROR_COUNT    5
#define ES_SAMPLE_COUNT   6
#define ES_EYESCAN_EN     7
#define ES_ERRDET_EN      8
#define ES_SDATA_MASK0    9
#define ES_SDATA_MASK1    10
#define ES_SDATA_MASK2    11
#define ES_SDATA_MASK3    12
#define ES_SDATA_MASK4    13
#define ES_QUAL_MASK0     14
#define ES_QUAL_MASK1     15
#define ES_QUAL_MASK2     16
#define ES_QUAL_MASK3     17
#define ES_QUAL_MASK4     18
#define ES_PMA_RSV2       19

//Constants to hold DRP address of various attributes (for 7 Series GTX transceiver)
#define DRP_ADDR_ES_CONTROL        0x03D
#define DRP_ADDR_ES_HORZ_OFFSET    0x03C
#define DRP_ADDR_ES_PRESCALE       0x03B
#define DRP_ADDR_ES_VERT_OFFSET    0x03B

#ifdef GTX
#define DRP_ADDR_ES_CONTROL_STATUS 0x151
#define DRP_ADDR_ES_ERROR_COUNT    0x14F
#define DRP_ADDR_ES_SAMPLE_COUNT   0x150
#define DRP_ADDR_ES_EYESCAN_EN     0x03D
#define DRP_START_BIT_ES_EYESCAN_EN  8
#define DRP_MASK_ES_EYESCAN_EN     0xFEFF

#define DRP_ADDR_PMA_RSV2          0x082
#define DRP_START_BIT_PMA_RSV2     5
#define DRP_MASK_PMA_RSV2          0xFFDF
#endif

#ifdef GTH
#define DRP_ADDR_ES_CONTROL_STATUS 0x153 //gth
#define DRP_ADDR_ES_ERROR_COUNT    0x151 //gth
#define DRP_ADDR_ES_SAMPLE_COUNT   0x152 //gth
#define DRP_ADDR_ES_EYESCAN_EN     0x03D
#define DRP_START_BIT_ES_EYESCAN_EN  8
#define DRP_MASK_ES_EYESCAN_EN     0xFEFF
#endif

#ifdef GTP
#define DRP_ADDR_ES_CONTROL_STATUS 0x153 //gtp
#define DRP_ADDR_ES_ERROR_COUNT    0x151 //gtp
#define DRP_ADDR_ES_SAMPLE_COUNT   0x152 //gtp
#define DRP_ADDR_ES_EYESCAN_EN     0x03D
#define DRP_START_BIT_ES_EYESCAN_EN  8
#define DRP_MASK_ES_EYESCAN_EN     0xFEFF
#endif



#define DRP_ADDR_ES_ERRDET_EN      0x03D
#define DRP_ADDR_ES_SDATA_MASK0    0x036
#define DRP_ADDR_ES_SDATA_MASK1    0x037
#define DRP_ADDR_ES_SDATA_MASK2    0x038
#define DRP_ADDR_ES_SDATA_MASK3    0x039
#define DRP_ADDR_ES_SDATA_MASK4    0x03A
#define DRP_ADDR_ES_QUAL_MASK0     0x031
#define DRP_ADDR_ES_QUAL_MASK1     0x032
#define DRP_ADDR_ES_QUAL_MASK2     0x033
#define DRP_ADDR_ES_QUAL_MASK3     0x034
#define DRP_ADDR_ES_QUAL_MASK4     0x035


//Constants to mask bits of various attributes (for 7 Series GTX transceiver)
#define DRP_MASK_ES_CONTROL        0xFFC0
#define DRP_MASK_ES_HORZ_OFFSET    0x0000
#define DRP_MASK_ES_PRESCALE       0x07FF
#define DRP_MASK_ES_VERT_OFFSET    0xFE00
#define DRP_MASK_ES_CONTROL_STATUS 0x0000
#define DRP_MASK_ES_ERROR_COUNT    0x0000
#define DRP_MASK_ES_SAMPLE_COUNT   0x0000
#define DRP_MASK_ES_ERRDET_EN      0xFDFF
#define DRP_MASK_ES_SDATA_MASK0    0x0000
#define DRP_MASK_ES_SDATA_MASK1    0x0000
#define DRP_MASK_ES_SDATA_MASK2    0x0000
#define DRP_MASK_ES_SDATA_MASK3    0x0000
#define DRP_MASK_ES_SDATA_MASK4    0x0000
#define DRP_MASK_ES_QUAL_MASK0     0x0000
#define DRP_MASK_ES_QUAL_MASK1     0x0000
#define DRP_MASK_ES_QUAL_MASK2     0x0000
#define DRP_MASK_ES_QUAL_MASK3     0x0000
#define DRP_MASK_ES_QUAL_MASK4     0x0000



//Constants to hold start bit of various attributes (for 7 Series GTX transceiver).  0 corresponds to LSB.
#define DRP_START_BIT_ES_CONTROL     0
#define DRP_START_BIT_ES_HORZ_OFFSET 0
#define DRP_START_BIT_ES_PRESCALE    11
#define DRP_START_BIT_ES_VERT_OFFSET 0
#define DRP_START_BIT_ES_CONTROL_STATUS 0
#define DRP_START_BIT_ES_ERROR_COUNT  0
#define DRP_START_BIT_ES_SAMPLE_COUNT 0
#define DRP_START_BIT_ES_ERRDET_EN   9
#define DRP_START_BIT_ES_SDATA_MASK0 0
#define DRP_START_BIT_ES_SDATA_MASK1 0
#define DRP_START_BIT_ES_SDATA_MASK2 0
#define DRP_START_BIT_ES_SDATA_MASK3 0
#define DRP_START_BIT_ES_SDATA_MASK4 0
#define DRP_START_BIT_ES_QUAL_MASK0  0
#define DRP_START_BIT_ES_QUAL_MASK1  0
#define DRP_START_BIT_ES_QUAL_MASK2  0
#define DRP_START_BIT_ES_QUAL_MASK3  0
#define DRP_START_BIT_ES_QUAL_MASK4  0

#ifndef DRP_H_
#define DRP_H_


//void drpModule_Initialize(drpModule * InstancePtr);

typedef struct  {
	u32 BaseAddress;
} drpModule;


static const u16 drp_addr[20] = {DRP_ADDR_ES_CONTROL,DRP_ADDR_ES_HORZ_OFFSET,DRP_ADDR_ES_PRESCALE,DRP_ADDR_ES_VERT_OFFSET
	,DRP_ADDR_ES_CONTROL_STATUS,DRP_ADDR_ES_ERROR_COUNT,DRP_ADDR_ES_SAMPLE_COUNT
	,DRP_ADDR_ES_EYESCAN_EN,DRP_ADDR_ES_ERRDET_EN
	,DRP_ADDR_ES_SDATA_MASK0, DRP_ADDR_ES_SDATA_MASK1, DRP_ADDR_ES_SDATA_MASK2, DRP_ADDR_ES_SDATA_MASK3, DRP_ADDR_ES_SDATA_MASK4
	,DRP_ADDR_ES_QUAL_MASK0, DRP_ADDR_ES_QUAL_MASK1, DRP_ADDR_ES_QUAL_MASK2, DRP_ADDR_ES_QUAL_MASK3, DRP_ADDR_ES_QUAL_MASK4, DRP_ADDR_PMA_RSV2};


static const u16 drp_start_bit[20] = {DRP_START_BIT_ES_CONTROL,DRP_START_BIT_ES_HORZ_OFFSET,DRP_START_BIT_ES_PRESCALE,DRP_START_BIT_ES_VERT_OFFSET
	,DRP_START_BIT_ES_CONTROL_STATUS,DRP_START_BIT_ES_ERROR_COUNT,DRP_START_BIT_ES_SAMPLE_COUNT
	,DRP_START_BIT_ES_EYESCAN_EN,DRP_START_BIT_ES_ERRDET_EN
	,DRP_START_BIT_ES_SDATA_MASK0, DRP_START_BIT_ES_SDATA_MASK1, DRP_START_BIT_ES_SDATA_MASK2, DRP_START_BIT_ES_SDATA_MASK3, DRP_START_BIT_ES_SDATA_MASK4
	,DRP_START_BIT_ES_QUAL_MASK0, DRP_START_BIT_ES_QUAL_MASK1, DRP_START_BIT_ES_QUAL_MASK2, DRP_START_BIT_ES_QUAL_MASK3, DRP_START_BIT_ES_QUAL_MASK4, DRP_START_BIT_PMA_RSV2};

static const u16 drp_mask[20] = {DRP_MASK_ES_CONTROL,DRP_MASK_ES_HORZ_OFFSET,DRP_MASK_ES_PRESCALE,DRP_MASK_ES_VERT_OFFSET
	,DRP_MASK_ES_CONTROL_STATUS,DRP_MASK_ES_ERROR_COUNT,DRP_MASK_ES_SAMPLE_COUNT
	,DRP_MASK_ES_EYESCAN_EN,DRP_MASK_ES_ERRDET_EN
	,DRP_MASK_ES_SDATA_MASK0, DRP_MASK_ES_SDATA_MASK1, DRP_MASK_ES_SDATA_MASK2, DRP_MASK_ES_SDATA_MASK3, DRP_MASK_ES_SDATA_MASK4
	,DRP_MASK_ES_QUAL_MASK0, DRP_MASK_ES_QUAL_MASK1, DRP_MASK_ES_QUAL_MASK2, DRP_MASK_ES_QUAL_MASK3, DRP_MASK_ES_QUAL_MASK4, DRP_MASK_PMA_RSV2};

u16 drp_write (drpModule* p_io_mod, s16 value, u8 pname, u8* lane_name, u8* block_name, u8* mode_name);
u16 drp_read  (drpModule* p_io_mod, u8 pname, u8* lane_name, u8* block_name, u8* mode_name);
u32 set_lane_offset (u8* lane_name);
u16 mask_drp_rddata (u16 value, u8 start_bit, u8 end_bit);

#endif /* DRP_H_ */
